name = "rusty-serp-dev"
main = "build/worker/shim.mjs"
compatibility_date = "2026-05-03"

[build]
command = "curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable && . \"$HOME/.cargo/env\" && rustup target add wasm32-unknown-unknown && cargo install -q worker-build && worker-build --release"

[env.staging]
name = "rusty-serp-staging"

[env.production]
name = "rusty-serp"
